//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int ID { get; set; }
        public int SaleID { get; set; }
        public int StoreID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string PaymentMethod { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
