//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemAttribute
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int ItemID { get; set; }
        public string Value { get; set; }
        public Nullable<float> Price { get; set; }
        public int StoreID { get; set; }
        public Nullable<bool> Visible { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Store Store { get; set; }
    }
}
