//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.Invoice = new HashSet<Invoice>();
            this.ItemPurchase = new HashSet<ItemPurchase>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public int StoreID { get; set; }
        public int ItemID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int ShiftID { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> DiscountRate { get; set; }
        public Nullable<decimal> TaxAmunt { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> SubtotalPrice { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoice { get; set; }
        public virtual Item Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemPurchase> ItemPurchase { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual Store Store { get; set; }
        public virtual Users Users { get; set; }
    }
}
